---
gateway : "192.168.1.1"
dns: "192.168.1.148"

easyrsa_version: "3.0.1"
easyrsa_dest: "/usr/share/easy-rsa"

easyrsa_dn: "cn_only"
easyrsa_req_country: "RU"
easyrsa_req_province: "Sankt-Peterburg"
easyrsa_req_city: "Sankt-Peterburg"
easyrsa_req_org: "Home Co"
easyrsa_req_email: "me@example.net"
easyrsa_req_ou: "Me"

easyrsa_keysize: 2048
easyrsa_digest: "sha256"

easyrsa_clients:
  - name: client1



vms_to_create:
 - name: "server"
   ip_address: "192.168.56.10/24"
   ip_address1:  "192.168.1.40/24"
   memory: "1024"
   
 - name: "client"
   ip_address: "192.168.56.20/24"
   ip_address1: "192.168.1.41/24"
   memory: "1024"
   
